// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Text;

#nullable enable

namespace Apache.Arrow.Serialization.Generator
{

/// <summary>
/// Emits a JSON schema descriptor as a static ArrowSchemaJson property.
/// The JSON describes the Arrow schema for cross-language codegen tools.
/// </summary>
internal static class JsonSchemaEmitter
{
    public static void Emit(StringBuilder sb, TypeModel model)
    {
        var json = BuildJson(model);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace != null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var typeKeyword = GetTypeKeyword(model);
        sb.AppendLine($"partial {typeKeyword} {model.TypeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string ArrowSchemaJson => @\"{json.Replace("\"", "\"\"")}\";");
        sb.AppendLine("}");
    }

    private static string BuildJson(TypeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("{");
        sb.AppendLine($"  \"type\": \"{JsonEscape(model.FullTypeName)}\",");
        sb.AppendLine($"  \"namespace\": {(model.Namespace != null ? $"\"{JsonEscape(model.Namespace)}\"" : "null")},");
        sb.AppendLine($"  \"typeName\": \"{JsonEscape(model.TypeName)}\",");

        // Metadata
        sb.Append("  \"metadata\": {");
        if (model.Metadata.Count > 0)
        {
            sb.AppendLine();
            for (int i = 0; i < model.Metadata.Count; i++)
            {
                var kv = model.Metadata[i];
                var comma = i < model.Metadata.Count - 1 ? "," : "";
                sb.AppendLine($"    \"{JsonEscape(kv.Key)}\": \"{JsonEscape(kv.Value)}\"{comma}");
            }
            sb.AppendLine("  },");
        }
        else
        {
            sb.AppendLine("},");
        }

        // Fields
        sb.AppendLine("  \"fields\": [");
        for (int i = 0; i < model.Properties.Count; i++)
        {
            var prop = model.Properties[i];
            var comma = i < model.Properties.Count - 1 ? "," : "";
            EmitField(sb, prop);
            // Remove trailing newline, add comma
            sb.Length -= sb.ToString().EndsWith("\r\n") ? 2 : 1;
            sb.AppendLine(comma);
        }
        sb.AppendLine("  ]");
        sb.Append("}");

        return sb.ToString();
    }

    private static void EmitField(StringBuilder sb, PropertyModel prop)
    {
        sb.AppendLine("    {");
        sb.AppendLine($"      \"name\": \"{JsonEscape(prop.FieldName)}\",");
        sb.AppendLine($"      \"propertyName\": \"{JsonEscape(prop.PropertyName)}\",");
        sb.AppendLine($"      \"arrowType\": \"{JsonEscape(GetArrowTypeName(prop.Type))}\",");
        sb.AppendLine($"      \"typeKind\": \"{prop.Type.Kind}\",");
        sb.AppendLine($"      \"nullable\": {(prop.IsNullable ? "true" : "false")},");
        sb.AppendLine($"      \"csharpType\": \"{JsonEscape(prop.Type.FullTypeName)}\"");

        if (prop.Type.ElementType != null)
        {
            // Replace last newline to add comma
            sb.Length -= sb.ToString().EndsWith("\r\n") ? 2 : 1;
            sb.AppendLine(",");
            sb.AppendLine($"      \"elementType\": \"{JsonEscape(GetArrowTypeName(prop.Type.ElementType))}\"");
        }

        if (prop.Type.KeyType != null)
        {
            sb.Length -= sb.ToString().EndsWith("\r\n") ? 2 : 1;
            sb.AppendLine(",");
            sb.AppendLine($"      \"keyType\": \"{JsonEscape(GetArrowTypeName(prop.Type.KeyType))}\",");
            sb.AppendLine($"      \"valueType\": \"{JsonEscape(GetArrowTypeName(prop.Type.ValueType!))}\"");
        }

        if (prop.ConverterTypeName != null)
        {
            sb.Length -= sb.ToString().EndsWith("\r\n") ? 2 : 1;
            sb.AppendLine(",");
            sb.AppendLine($"      \"converter\": \"{JsonEscape(prop.ConverterTypeName)}\"");
        }

        if (prop.Metadata.Count > 0)
        {
            sb.Length -= sb.ToString().EndsWith("\r\n") ? 2 : 1;
            sb.AppendLine(",");
            sb.Append("      \"metadata\": {");
            sb.AppendLine();
            for (int j = 0; j < prop.Metadata.Count; j++)
            {
                var kv = prop.Metadata[j];
                var mComma = j < prop.Metadata.Count - 1 ? "," : "";
                sb.AppendLine($"        \"{JsonEscape(kv.Key)}\": \"{JsonEscape(kv.Value)}\"{mComma}");
            }
            sb.AppendLine("      }");
        }

        sb.AppendLine("    }");
    }

    private static string GetArrowTypeName(TypeInfo type)
    {
        if (type.ArrowTypeOverride != null)
            return type.ArrowTypeOverride;

        return type.Kind switch
        {
            TypeKind2.String => "utf8",
            TypeKind2.Bool => "bool",
            TypeKind2.Byte => "uint8",
            TypeKind2.SByte => "int8",
            TypeKind2.Int16 => "int16",
            TypeKind2.UInt16 => "uint16",
            TypeKind2.Int32 => "int32",
            TypeKind2.UInt32 => "uint32",
            TypeKind2.Int64 => "int64",
            TypeKind2.UInt64 => "uint64",
            TypeKind2.Float => "float32",
            TypeKind2.Double => "float64",
            TypeKind2.Decimal => "decimal128(38,18)",
            TypeKind2.Binary => "binary",
            TypeKind2.DateTime => "timestamp[us, UTC]",
            TypeKind2.DateTimeOffset => "timestamp[us, UTC]",
            TypeKind2.DateOnly => "date32",
            TypeKind2.TimeOnly => "time64[us]",
            TypeKind2.TimeSpan => "duration[us]",
            TypeKind2.Guid => "fixed_size_binary(16)",
            TypeKind2.Half => "float16",
            TypeKind2.Enum => "dictionary<int16, utf8>",
            TypeKind2.List => $"list<{GetArrowTypeName(type.ElementType!)}>",
            TypeKind2.Array => $"list<{GetArrowTypeName(type.ElementType!)}>",
            TypeKind2.Set => $"list<{GetArrowTypeName(type.ElementType!)}>",
            TypeKind2.Dictionary => $"map<{GetArrowTypeName(type.KeyType!)}, {GetArrowTypeName(type.ValueType!)}>",
            TypeKind2.NestedRecord => $"struct<{type.FullTypeName}>",
            TypeKind2.Custom => "custom",
            _ => "unknown",
        };
    }

    private static string GetTypeKeyword(TypeModel model)
    {
        if (model.IsRecord && model.IsValueType) return "record struct";
        if (model.IsRecord) return "record";
        if (model.IsValueType) return "struct";
        return "class";
    }

    private static string JsonEscape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
}

} // namespace
