// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Text;

#nullable enable

namespace Apache.Arrow.Serialization.Generator
{

    internal class PolymorphicCodeEmitter
    {
        private readonly StringBuilder _sb;
        private readonly PolymorphicModel _model;
        private int _indent;

        public PolymorphicCodeEmitter(StringBuilder sb, PolymorphicModel model)
        {
            _sb = sb;
            _model = model;
        }

        public void Emit()
        {
            Line("// <auto-generated/>");
            Line("#nullable enable");
            Line("#pragma warning disable CS8629 // Nullable value type may be null");
            Line("#pragma warning disable CS0162 // Unreachable code after NotSupportedException throws");
            Line();
            Line("using System.Collections.Generic;");
            Line("using System.Linq;");
            Line("using Apache.Arrow;");
            Line("using Apache.Arrow.Arrays;");
            Line("using Apache.Arrow.Types;");
            Line("using Apache.Arrow.Serialization;");
            Line();

            if (_model.Namespace != null)
            {
                Line($"namespace {_model.Namespace};");
                Line();
            }

            var typeKeyword = _model.IsInterface ? "interface" : (_model.IsRecord ? "record" : "class");
            Line($"partial {typeKeyword} {_model.TypeName} : IArrowSerializable");
            Line("{");
            _indent++;

            EmitSchemaField();
            Line();
            EmitSerialize();
            Line();
            EmitDeserialize();
            Line();
            EmitMultiRowSerialize();
            Line();
            EmitMultiRowDeserialize();

            _indent--;
            Line("}");
            Line();
            CodeEmitterHelpers.EmitSerializerRegistration(Line, _model.TypeName);
        }

        private void EmitSchemaField()
        {
            Line($"private static readonly Schema _arrowSchema = new Schema.Builder()");
            _indent++;

            // Discriminator field
            Line($".Field(new Field(\"{Escape(_model.TypeDiscriminatorFieldName)}\", StringType.Default, false))");

            // Union properties — all nullable
            foreach (var prop in _model.UnionProperties)
            {
                var arrowType = CodeEmitterHelpers.GetArrowTypeExpression(prop.Type);
                Line($".Field(new Field(\"{Escape(prop.FieldName)}\", {arrowType}, true))");
            }

            _indent--;
            Line($".Build();");
            Line();
            Line($"public static Schema ArrowSchema => _arrowSchema;");
        }

        private void EmitSerialize()
        {
            Line($"public static RecordBatch ToRecordBatch({_model.TypeName} value)");
            Line("{");
            _indent++;

            // Build discriminator column
            Line("var discriminatorBuilder = new StringArray.Builder();");

            // Build union property builders
            for (int i = 0; i < _model.UnionProperties.Count; i++)
            {
                var prop = _model.UnionProperties[i];
                EmitBuilderDeclaration(prop, i);
            }

            Line();
            // Switch on concrete type
            Line("switch (value)");
            Line("{");
            _indent++;

            foreach (var dt in _model.DerivedTypes)
            {
                Line($"case {dt.FullTypeName} v_{dt.TypeName}:");
                Line("{");
                _indent++;
                Line($"discriminatorBuilder.Append(\"{Escape(dt.TypeDiscriminator)}\");");

                // For each union property, either append the value or null
                for (int i = 0; i < _model.UnionProperties.Count; i++)
                {
                    var unionProp = _model.UnionProperties[i];
                    var derivedProp = FindProperty(dt, unionProp.FieldName);
                    if (derivedProp != null)
                    {
                        EmitAppendValue(derivedProp, i, $"v_{dt.TypeName}.{derivedProp.PropertyName}");
                    }
                    else
                    {
                        EmitAppendNull(unionProp, i);
                    }
                }

                Line("break;");
                _indent--;
                Line("}");
            }

            Line($"default:");
            _indent++;
            Line($"throw new System.ArgumentException($\"Unknown derived type: {{value.GetType().Name}}\");");
            _indent--;

            _indent--;
            Line("}");

            Line();
            // Build arrays and RecordBatch
            Line("var columns = new IArrowArray[]");
            Line("{");
            _indent++;
            Line("discriminatorBuilder.Build(),");
            for (int i = 0; i < _model.UnionProperties.Count; i++)
            {
                EmitBuildColumn(i);
            }
            _indent--;
            Line("};");
            Line("return new RecordBatch(_arrowSchema, columns, 1);");

            _indent--;
            Line("}");
        }

        private void EmitDeserialize()
        {
            Line($"public static {_model.TypeName} FromRecordBatch(RecordBatch batch)");
            Line("{");
            _indent++;

            Line("var discriminator = ((StringArray)batch.Column(0)).GetString(0)!;");
            Line("switch (discriminator)");
            Line("{");
            _indent++;

            foreach (var dt in _model.DerivedTypes)
            {
                Line($"case \"{Escape(dt.TypeDiscriminator)}\":");
                Line("{");
                _indent++;

                // Read each property for this derived type from the batch columns
                for (int i = 0; i < dt.Properties.Count; i++)
                {
                    var prop = dt.Properties[i];
                    var unionIndex = FindUnionPropertyIndex(prop.FieldName);
                    var colIndex = unionIndex + 1; // +1 for discriminator
                    EmitReadProperty(prop, i, colIndex);
                }

                // Construct the derived type
                Line($"return new {dt.FullTypeName}");
                Line("{");
                _indent++;
                for (int i = 0; i < dt.Properties.Count; i++)
                {
                    var prop = dt.Properties[i];
                    Line($"{prop.PropertyName} = prop_{i},");
                }
                _indent--;
                Line("};");

                _indent--;
                Line("}");
            }

            Line("default:");
            _indent++;
            Line("throw new System.ArgumentException($\"Unknown type discriminator: {discriminator}\");");
            _indent--;

            _indent--;
            Line("}");

            _indent--;
            Line("}");
        }

        private void EmitMultiRowSerialize()
        {
            Line($"public static RecordBatch ToRecordBatch(IReadOnlyList<{_model.TypeName}> values)");
            Line("{");
            _indent++;

            Line("var discriminatorBuilder = new StringArray.Builder();");
            for (int i = 0; i < _model.UnionProperties.Count; i++)
            {
                var prop = _model.UnionProperties[i];
                EmitBuilderDeclaration(prop, i);
            }

            Line();
            Line("foreach (var value in values)");
            Line("{");
            _indent++;

            Line("switch (value)");
            Line("{");
            _indent++;

            foreach (var dt in _model.DerivedTypes)
            {
                Line($"case {dt.FullTypeName} v_{dt.TypeName}:");
                Line("{");
                _indent++;
                Line($"discriminatorBuilder.Append(\"{Escape(dt.TypeDiscriminator)}\");");

                for (int i = 0; i < _model.UnionProperties.Count; i++)
                {
                    var unionProp = _model.UnionProperties[i];
                    var derivedProp = FindProperty(dt, unionProp.FieldName);
                    if (derivedProp != null)
                    {
                        EmitAppendValue(derivedProp, i, $"v_{dt.TypeName}.{derivedProp.PropertyName}");
                    }
                    else
                    {
                        EmitAppendNull(unionProp, i);
                    }
                }

                Line("break;");
                _indent--;
                Line("}");
            }

            Line($"default:");
            _indent++;
            Line($"throw new System.ArgumentException($\"Unknown derived type: {{value.GetType().Name}}\");");
            _indent--;

            _indent--;
            Line("}");

            _indent--;
            Line("}");

            Line();
            Line("var columns = new IArrowArray[]");
            Line("{");
            _indent++;
            Line("discriminatorBuilder.Build(),");
            for (int i = 0; i < _model.UnionProperties.Count; i++)
            {
                EmitBuildColumn(i);
            }
            _indent--;
            Line("};");
            Line("return new RecordBatch(_arrowSchema, columns, values.Count);");

            _indent--;
            Line("}");
        }

        private void EmitBuildColumn(int index)
        {
            var prop = _model.UnionProperties[index];
            if (prop.Type.Kind == ArrowTypeKind.Enum)
            {
                // Build DictionaryArray from index + dict builders
                Line($"new DictionaryArray(new DictionaryType(Int16Type.Default, StringType.Default, false), bld_{index}_idx.Build(), new StringArray.Builder().AppendRange(bld_{index}_dict).Build()),");
            }
            else
            {
                Line($"bld_{index}.Build(),");
            }
        }

        private void EmitMultiRowDeserialize()
        {
            Line($"public static IReadOnlyList<{_model.TypeName}> ListFromRecordBatch(RecordBatch batch)");
            Line("{");
            _indent++;

            Line("var discriminatorCol = (StringArray)batch.Column(0);");

            // Cast all union property columns
            for (int i = 0; i < _model.UnionProperties.Count; i++)
            {
                var prop = _model.UnionProperties[i];
                var colIndex = i + 1;
                var castType = CodeEmitterHelpers.GetArrayCastType(prop);
                Line($"var col_{i} = ({castType})batch.Column({colIndex});");
            }

            Line();
            Line($"var result = new List<{_model.TypeName}>(batch.Length);");
            Line("for (int row = 0; row < batch.Length; row++)");
            Line("{");
            _indent++;

            Line("var discriminator = discriminatorCol.GetString(row)!;");
            Line("switch (discriminator)");
            Line("{");
            _indent++;

            foreach (var dt in _model.DerivedTypes)
            {
                Line($"case \"{Escape(dt.TypeDiscriminator)}\":");
                Line("{");
                _indent++;

                for (int i = 0; i < dt.Properties.Count; i++)
                {
                    var prop = dt.Properties[i];
                    var unionIndex = FindUnionPropertyIndex(prop.FieldName);
                    EmitMultiRowReadProperty(prop, i, unionIndex);
                }

                Line($"result.Add(new {dt.FullTypeName}");
                Line("{");
                _indent++;
                for (int i = 0; i < dt.Properties.Count; i++)
                {
                    var prop = dt.Properties[i];
                    Line($"{prop.PropertyName} = prop_{i},");
                }
                _indent--;
                Line("});");
                Line("break;");

                _indent--;
                Line("}");
            }

            Line("default:");
            _indent++;
            Line("throw new System.ArgumentException($\"Unknown type discriminator: {discriminator}\");");
            _indent--;

            _indent--;
            Line("}");

            _indent--;
            Line("}");
            Line("return result;");

            _indent--;
            Line("}");
        }

        // --- Helpers ---

        private void EmitBuilderDeclaration(PropertyModel prop, int index)
        {
            if (prop.Type.Kind == ArrowTypeKind.Enum)
            {
                // Enum uses Dictionary(Int16, Utf8) — built manually.
                // The lookup deduplicates repeated values so each name appears once in the dictionary.
                Line($"var bld_{index}_idx = new Int16Array.Builder();");
                Line($"var bld_{index}_dict = new List<string>();");
                Line($"var bld_{index}_lookup = new Dictionary<string, short>();");
            }
            else
            {
                var builderType = CodeEmitterHelpers.GetNullableBuilderDeclaration(prop);
                Line($"var bld_{index} = {builderType};");
            }
        }

        private void EmitAppendValue(PropertyModel prop, int index, string access)
        {
            // For non-nullable properties in the derived type, we still need to handle them
            // as nullable in the union schema
            switch (prop.Type.Kind)
            {
                case ArrowTypeKind.String:
                    if (prop.IsNullable)
                        Line($"if ({access} != null) bld_{index}.Append({access}); else bld_{index}.AppendNull();");
                    else
                        Line($"bld_{index}.Append({access});");
                    break;
                case ArrowTypeKind.Bool:
                case ArrowTypeKind.Byte:
                case ArrowTypeKind.SByte:
                case ArrowTypeKind.Int16:
                case ArrowTypeKind.UInt16:
                case ArrowTypeKind.Int32:
                case ArrowTypeKind.UInt32:
                case ArrowTypeKind.Int64:
                case ArrowTypeKind.UInt64:
                case ArrowTypeKind.Float:
                case ArrowTypeKind.Double:
                case ArrowTypeKind.Half:
                    if (prop.IsNullable)
                        Line($"if ({access} is {{ }} v_{index}) bld_{index}.Append(v_{index}); else bld_{index}.AppendNull();");
                    else
                        Line($"bld_{index}.Append({access});");
                    break;
                case ArrowTypeKind.DateTime:
                case ArrowTypeKind.DateTimeOffset:
                    if (prop.IsNullable)
                        Line($"if ({access} is {{ }} v_{index}) bld_{index}.Append(Apache.Arrow.Serialization.ArrowArrayHelper.ToUtcDateTimeOffset(v_{index})); else bld_{index}.AppendNull();");
                    else
                        Line($"bld_{index}.Append(Apache.Arrow.Serialization.ArrowArrayHelper.ToUtcDateTimeOffset({access}));");
                    break;
                case ArrowTypeKind.DateOnly:
                    if (prop.IsNullable)
                        Line($"if ({access} is {{ }} v_{index}) bld_{index}.Append(v_{index}); else bld_{index}.AppendNull();");
                    else
                        Line($"bld_{index}.Append({access});");
                    break;
                case ArrowTypeKind.Decimal:
                    if (prop.IsNullable)
                        Line($"if ({access} is {{ }} v_{index}) bld_{index}.Append(v_{index}); else bld_{index}.AppendNull();");
                    else
                        Line($"bld_{index}.Append({access});");
                    break;
                case ArrowTypeKind.Enum:
                    if (prop.IsNullable)
                    {
                        Line($"if ({access} is {{ }} v_{index}) {{ var name_{index} = v_{index}.ToString(); if (!bld_{index}_lookup.TryGetValue(name_{index}, out var dictIdx_{index})) {{ dictIdx_{index} = (short)bld_{index}_dict.Count; bld_{index}_lookup[name_{index}] = dictIdx_{index}; bld_{index}_dict.Add(name_{index}); }} bld_{index}_idx.Append(dictIdx_{index}); }} else bld_{index}_idx.AppendNull();");
                    }
                    else
                    {
                        Line($"var name_{index} = {access}.ToString();");
                        Line($"if (!bld_{index}_lookup.TryGetValue(name_{index}, out var dictIdx_{index})) {{ dictIdx_{index} = (short)bld_{index}_dict.Count; bld_{index}_lookup[name_{index}] = dictIdx_{index}; bld_{index}_dict.Add(name_{index}); }}");
                        Line($"bld_{index}_idx.Append(dictIdx_{index});");
                    }
                    break;
                default:
                    // Complex types (Binary, Guid, TimeOnly, TimeSpan, nested records, collections)
                    // are not supported in polymorphic hierarchies — fail loudly instead of losing data.
                    Line($"throw new System.NotSupportedException(\"Property '{prop.PropertyName}' of type kind {prop.Type.Kind} is not supported in polymorphic Arrow serialization.\");");
                    break;
            }
        }

        private void EmitAppendNull(PropertyModel prop, int index)
        {
            if (prop.Type.Kind == ArrowTypeKind.Enum)
                Line($"bld_{index}_idx.AppendNull();");
            else
                Line($"bld_{index}.AppendNull();");
        }

        private void EmitReadProperty(PropertyModel prop, int propIndex, int colIndex)
        {
            var col = $"batch.Column({colIndex})";
            switch (prop.Type.Kind)
            {
                case ArrowTypeKind.String:
                    if (prop.IsNullable)
                        Line($"var prop_{propIndex} = ((StringArray){col}).IsNull(0) ? null : ((StringArray){col}).GetString(0);");
                    else
                        Line($"var prop_{propIndex} = ((StringArray){col}).GetString(0)!;");
                    break;
                case ArrowTypeKind.Bool:
                case ArrowTypeKind.Byte:
                case ArrowTypeKind.SByte:
                case ArrowTypeKind.Int16:
                case ArrowTypeKind.UInt16:
                case ArrowTypeKind.Int32:
                case ArrowTypeKind.UInt32:
                case ArrowTypeKind.Int64:
                case ArrowTypeKind.UInt64:
                case ArrowTypeKind.Float:
                case ArrowTypeKind.Double:
                case ArrowTypeKind.Half:
                    {
                        var castType = CodeEmitterHelpers.GetArrayCastType(prop);
                        if (prop.IsNullable)
                            Line($"var prop_{propIndex} = (({castType}){col}).IsNull(0) ? ({prop.Type.FullTypeName}?)null : (({castType}){col}).GetValue(0).Value;");
                        else
                            Line($"var prop_{propIndex} = (({castType}){col}).GetValue(0).Value;");
                        break;
                    }
                case ArrowTypeKind.DateTime:
                    {
                        if (prop.IsNullable)
                            Line($"var prop_{propIndex} = ((TimestampArray){col}).IsNull(0) ? (System.DateTime?)null : ((TimestampArray){col}).GetTimestamp(0)!.Value.UtcDateTime;");
                        else
                            Line($"var prop_{propIndex} = ((TimestampArray){col}).GetTimestamp(0)!.Value.UtcDateTime;");
                        break;
                    }
                case ArrowTypeKind.DateTimeOffset:
                    {
                        if (prop.IsNullable)
                            Line($"var prop_{propIndex} = ((TimestampArray){col}).IsNull(0) ? (System.DateTimeOffset?)null : ((TimestampArray){col}).GetTimestamp(0)!.Value;");
                        else
                            Line($"var prop_{propIndex} = ((TimestampArray){col}).GetTimestamp(0)!.Value;");
                        break;
                    }
                case ArrowTypeKind.DateOnly:
                    {
                        var castType = CodeEmitterHelpers.GetArrayCastType(prop);
                        if (prop.IsNullable)
                            Line($"var prop_{propIndex} = (({castType}){col}).IsNull(0) ? (System.DateOnly?)null : (({castType}){col}).GetDateOnly(0);");
                        else
                            Line($"var prop_{propIndex} = (({castType}){col}).GetDateOnly(0)!.Value;");
                        break;
                    }
                case ArrowTypeKind.Decimal:
                    {
                        if (prop.IsNullable)
                            Line($"var prop_{propIndex} = ((Decimal128Array){col}).IsNull(0) ? (decimal?)null : ((Decimal128Array){col}).GetValue(0).Value;");
                        else
                            Line($"var prop_{propIndex} = ((Decimal128Array){col}).GetValue(0)!.Value;");
                        break;
                    }
                case ArrowTypeKind.Enum:
                    {
                        var enumType = prop.Type.FullTypeName;
                        if (prop.IsNullable)
                        {
                            Line($"{enumType}? prop_{propIndex} = null;");
                            Line($"{{ var da = (DictionaryArray){col}; if (!da.IsNull(0)) {{ var idx = ((Int16Array)da.Indices).GetValue(0).Value; var name = ((StringArray)da.Dictionary).GetString(idx); prop_{propIndex} = ArrowArrayHelper.ParseEnum<{enumType}>(name!); }} }}");
                        }
                        else
                        {
                            Line($"var da_{propIndex} = (DictionaryArray){col};");
                            Line($"var idx_{propIndex} = ((Int16Array)da_{propIndex}.Indices).GetValue(0).Value;");
                            Line($"var prop_{propIndex} = ArrowArrayHelper.ParseEnum<{enumType}>(((StringArray)da_{propIndex}.Dictionary).GetString(idx_{propIndex})!);");
                        }
                        break;
                    }
                default:
                    Line($"var prop_{propIndex} = Apache.Arrow.Serialization.ArrowArrayHelper.ThrowNotSupported<{prop.Type.FullTypeName}>(\"Property '{prop.PropertyName}' of type kind {prop.Type.Kind} is not supported in polymorphic Arrow serialization.\");");
                    break;
            }
        }

        private void EmitMultiRowReadProperty(PropertyModel prop, int propIndex, int unionIndex)
        {
            var col = $"col_{unionIndex}";
            switch (prop.Type.Kind)
            {
                case ArrowTypeKind.String:
                    if (prop.IsNullable)
                        Line($"var prop_{propIndex} = {col}.IsNull(row) ? null : {col}.GetString(row);");
                    else
                        Line($"var prop_{propIndex} = {col}.GetString(row)!;");
                    break;
                case ArrowTypeKind.Bool:
                case ArrowTypeKind.Byte:
                case ArrowTypeKind.SByte:
                case ArrowTypeKind.Int16:
                case ArrowTypeKind.UInt16:
                case ArrowTypeKind.Int32:
                case ArrowTypeKind.UInt32:
                case ArrowTypeKind.Int64:
                case ArrowTypeKind.UInt64:
                case ArrowTypeKind.Float:
                case ArrowTypeKind.Double:
                case ArrowTypeKind.Half:
                    if (prop.IsNullable)
                        Line($"var prop_{propIndex} = {col}.IsNull(row) ? ({prop.Type.FullTypeName}?)null : {col}.GetValue(row).Value;");
                    else
                        Line($"var prop_{propIndex} = {col}.GetValue(row).Value;");
                    break;
                case ArrowTypeKind.DateTime:
                    if (prop.IsNullable)
                        Line($"var prop_{propIndex} = {col}.IsNull(row) ? (System.DateTime?)null : {col}.GetTimestamp(row)!.Value.UtcDateTime;");
                    else
                        Line($"var prop_{propIndex} = {col}.GetTimestamp(row)!.Value.UtcDateTime;");
                    break;
                case ArrowTypeKind.DateTimeOffset:
                    if (prop.IsNullable)
                        Line($"var prop_{propIndex} = {col}.IsNull(row) ? (System.DateTimeOffset?)null : {col}.GetTimestamp(row)!.Value;");
                    else
                        Line($"var prop_{propIndex} = {col}.GetTimestamp(row)!.Value;");
                    break;
                case ArrowTypeKind.DateOnly:
                    if (prop.IsNullable)
                        Line($"var prop_{propIndex} = {col}.IsNull(row) ? (System.DateOnly?)null : {col}.GetDateOnly(row);");
                    else
                        Line($"var prop_{propIndex} = {col}.GetDateOnly(row)!.Value;");
                    break;
                case ArrowTypeKind.Decimal:
                    if (prop.IsNullable)
                        Line($"var prop_{propIndex} = {col}.IsNull(row) ? (decimal?)null : {col}.GetValue(row).Value;");
                    else
                        Line($"var prop_{propIndex} = {col}.GetValue(row)!.Value;");
                    break;
                case ArrowTypeKind.Enum:
                    {
                        var enumType = prop.Type.FullTypeName;
                        if (prop.IsNullable)
                        {
                            Line($"{enumType}? prop_{propIndex} = null;");
                            Line($"if (!{col}.IsNull(row)) {{ var idx = ((Int16Array){col}.Indices).GetValue(row).Value; var name = ((StringArray){col}.Dictionary).GetString(idx); prop_{propIndex} = ArrowArrayHelper.ParseEnum<{enumType}>(name!); }}");
                        }
                        else
                        {
                            Line($"var idx_{propIndex} = ((Int16Array){col}.Indices).GetValue(row).Value;");
                            Line($"var prop_{propIndex} = ArrowArrayHelper.ParseEnum<{enumType}>(((StringArray){col}.Dictionary).GetString(idx_{propIndex})!);");
                        }
                        break;
                    }
                default:
                    Line($"var prop_{propIndex} = Apache.Arrow.Serialization.ArrowArrayHelper.ThrowNotSupported<{prop.Type.FullTypeName}>(\"Property '{prop.PropertyName}' of type kind {prop.Type.Kind} is not supported in polymorphic Arrow serialization.\");");
                    break;
            }
        }

        private static PropertyModel? FindProperty(DerivedTypeInfo dt, string fieldName)
        {
            foreach (var prop in dt.Properties)
            {
                if (prop.FieldName == fieldName)
                    return prop;
            }
            return null;
        }

        private int FindUnionPropertyIndex(string fieldName)
        {
            for (int i = 0; i < _model.UnionProperties.Count; i++)
            {
                if (_model.UnionProperties[i].FieldName == fieldName)
                    return i;
            }
            return -1;
        }

        private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private void Line(string text = "")
        {
            if (string.IsNullOrEmpty(text))
            {
                _sb.AppendLine();
                return;
            }
            _sb.Append(' ', _indent * 4);
            _sb.AppendLine(text);
        }
    }

    /// <summary>
    /// Shared helpers used by both CodeEmitter and PolymorphicCodeEmitter.
    /// </summary>
    internal static class CodeEmitterHelpers
    {
        /// <summary>
        /// Emits a registration class with an IArrowSerializer&lt;T&gt; implementation that
        /// delegates to the generated statics, registered via module initializer so the
        /// ArrowSerializerRegistry is populated before any user code in the assembly runs.
        /// </summary>
        public static void EmitSerializerRegistration(Action<string> line, string typeName)
        {
            line($"internal static class {typeName}ArrowSerializerRegistration");
            line("{");
            line($"    private sealed class Serializer : IArrowSerializer<{typeName}>");
            line("    {");
            line($"        public Schema ArrowSchema => {typeName}.ArrowSchema;");
            line($"        public RecordBatch ToRecordBatch({typeName} value) => {typeName}.ToRecordBatch(value);");
            line($"        public {typeName} FromRecordBatch(RecordBatch batch) => {typeName}.FromRecordBatch(batch);");
            line($"        public RecordBatch ToRecordBatch(IReadOnlyList<{typeName}> values) => {typeName}.ToRecordBatch(values);");
            line($"        public IReadOnlyList<{typeName}> ListFromRecordBatch(RecordBatch batch) => {typeName}.ListFromRecordBatch(batch);");
            line("    }");
            line("");
            line("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            line("    internal static void Register() =>");
            line($"        ArrowSerializerRegistry.Register<{typeName}>(new Serializer());");
            line("}");
        }

        /// <summary>
        /// Returns the Arrow type expression for a TypeInfo (e.g., "Int32Type.Default").
        /// </summary>
        public static string GetArrowTypeExpression(TypeInfo type)
        {
            if (type.ArrowTypeOverride != null)
                return ParseArrowTypeOverride(type.ArrowTypeOverride);

            return type.Kind switch
            {
                ArrowTypeKind.String => "StringType.Default",
                ArrowTypeKind.Bool => "BooleanType.Default",
                ArrowTypeKind.Byte => "UInt8Type.Default",
                ArrowTypeKind.SByte => "Int8Type.Default",
                ArrowTypeKind.Int16 => "Int16Type.Default",
                ArrowTypeKind.UInt16 => "UInt16Type.Default",
                ArrowTypeKind.Int32 => "Int32Type.Default",
                ArrowTypeKind.UInt32 => "UInt32Type.Default",
                ArrowTypeKind.Int64 => "Int64Type.Default",
                ArrowTypeKind.UInt64 => "UInt64Type.Default",
                ArrowTypeKind.Float => "FloatType.Default",
                ArrowTypeKind.Double => "DoubleType.Default",
                ArrowTypeKind.Decimal => "new Decimal128Type(38, 18)",
                ArrowTypeKind.Binary => "BinaryType.Default",
                ArrowTypeKind.DateTime => "new TimestampType(TimeUnit.Microsecond, \"UTC\")",
                ArrowTypeKind.DateTimeOffset => "new TimestampType(TimeUnit.Microsecond, \"UTC\")",
                ArrowTypeKind.DateOnly => "Date32Type.Default",
                ArrowTypeKind.TimeOnly => "new Time64Type(TimeUnit.Microsecond)",
                ArrowTypeKind.TimeSpan => "DurationType.Microsecond",
                ArrowTypeKind.Guid => "GuidType.Default",
                ArrowTypeKind.Half => "HalfFloatType.Default",
                ArrowTypeKind.Enum => "new DictionaryType(Int16Type.Default, StringType.Default, false)",
                ArrowTypeKind.List or ArrowTypeKind.Array or ArrowTypeKind.Set =>
                    $"new ListType(new Field(\"item\", {GetArrowTypeExpression(type.ElementType!)}, {(type.ElementType!.IsNullable ? "true" : "false")}))",
                ArrowTypeKind.Dictionary =>
                    $"new MapType(new Field(\"key\", {GetArrowTypeExpression(type.KeyType!)}, false), new Field(\"value\", {GetArrowTypeExpression(type.ValueType!)}, true))",
                ArrowTypeKind.NestedRecord =>
                    $"new StructType({type.FullTypeName}.ArrowSchema.FieldsList)",
                _ => "StringType.Default /* unsupported */",
            };
        }

        private static string ParseArrowTypeOverride(string typeName)
        {
            var lower = typeName.ToLowerInvariant().Trim();
            return lower switch
            {
                "date32" => "Date32Type.Default",
                "date64" => "Date64Type.Default",
                _ => $"StringType.Default /* unrecognized: {typeName} */",
            };
        }

        /// <summary>
        /// Returns the Arrow array type for casting (e.g., "Int32Array", "StringArray").
        /// </summary>
        public static string GetArrayCastType(PropertyModel prop)
        {
            return prop.Type.Kind switch
            {
                ArrowTypeKind.String => "StringArray",
                ArrowTypeKind.Bool => "BooleanArray",
                ArrowTypeKind.Byte => "UInt8Array",
                ArrowTypeKind.SByte => "Int8Array",
                ArrowTypeKind.Int16 => "Int16Array",
                ArrowTypeKind.UInt16 => "UInt16Array",
                ArrowTypeKind.Int32 => "Int32Array",
                ArrowTypeKind.UInt32 => "UInt32Array",
                ArrowTypeKind.Int64 => "Int64Array",
                ArrowTypeKind.UInt64 => "UInt64Array",
                ArrowTypeKind.Float => "FloatArray",
                ArrowTypeKind.Double => "DoubleArray",
                ArrowTypeKind.Half => "HalfFloatArray",
                ArrowTypeKind.Decimal => "Decimal128Array",
                ArrowTypeKind.DateTime => "TimestampArray",
                ArrowTypeKind.DateTimeOffset => "TimestampArray",
                ArrowTypeKind.DateOnly => "Date32Array",
                ArrowTypeKind.TimeOnly => "Time64Array",
                ArrowTypeKind.TimeSpan => "DurationArray",
                ArrowTypeKind.Guid => "GuidArray",
                ArrowTypeKind.Binary => "BinaryArray",
                ArrowTypeKind.Enum => "DictionaryArray",
                ArrowTypeKind.List or ArrowTypeKind.Array or ArrowTypeKind.Set => "ListArray",
                ArrowTypeKind.Dictionary => "MapArray",
                ArrowTypeKind.NestedRecord => "StructArray",
                _ => "IArrowArray",
            };
        }

        /// <summary>
        /// Returns a "new SomeBuilder()" expression for nullable builders.
        /// </summary>
        public static string GetNullableBuilderDeclaration(PropertyModel prop)
        {
            switch (prop.Type.Kind)
            {
                case ArrowTypeKind.String:
                    return "new StringArray.Builder()";
                case ArrowTypeKind.Bool:
                    return "new BooleanArray.Builder()";
                case ArrowTypeKind.Byte:
                    return "new UInt8Array.Builder()";
                case ArrowTypeKind.SByte:
                    return "new Int8Array.Builder()";
                case ArrowTypeKind.Int16:
                    return "new Int16Array.Builder()";
                case ArrowTypeKind.UInt16:
                    return "new UInt16Array.Builder()";
                case ArrowTypeKind.Int32:
                    return "new Int32Array.Builder()";
                case ArrowTypeKind.UInt32:
                    return "new UInt32Array.Builder()";
                case ArrowTypeKind.Int64:
                    return "new Int64Array.Builder()";
                case ArrowTypeKind.UInt64:
                    return "new UInt64Array.Builder()";
                case ArrowTypeKind.Float:
                    return "new FloatArray.Builder()";
                case ArrowTypeKind.Double:
                    return "new DoubleArray.Builder()";
                case ArrowTypeKind.Half:
                    return "new HalfFloatArray.Builder()";
                case ArrowTypeKind.Decimal:
                    return "new Decimal128Array.Builder(new Decimal128Type(38, 18))";
                case ArrowTypeKind.DateTime:
                case ArrowTypeKind.DateTimeOffset:
                    return "new TimestampArray.Builder(new TimestampType(TimeUnit.Microsecond, \"UTC\"))";
                case ArrowTypeKind.DateOnly:
                    return "new Date32Array.Builder()";
                case ArrowTypeKind.TimeOnly:
                    return "new Time64Array.Builder(Time64Type.Default)";
                case ArrowTypeKind.TimeSpan:
                    return "new DurationArray.Builder(DurationType.Microsecond)";
                default:
                    return $"new StringArray.Builder() /* fallback for {prop.Type.Kind} */";
            }
        }
    }

} // namespace
